version: "3.5"

# REF: https://www.cloudbooklet.com/how-to-install-nginx-and-lets-encrypt-with-docker-ubuntu-20-04/

services:

  gateway:
    image: pocket-network/gateway
    build:
      context: ../gateway
      dockerfile: ./Dockerfile
    command: npm run start:watch
    env_file:
      - ./.gateway.env
    environment:
      - WATCH=${WATCH:-false}
      - NODE_ENV=development
    volumes:
      - "../gateway/src:/usr/src/gateway/src"
      - "../gateway/dist:/usr/src/gateway/dist"
    ports:
      - 3000:3000
    networks:
      - poktnet

  db:
    image: mongo:latest
    env_file:
      - ./.db.env
    volumes: 
      - ~/.pocket/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - poktnet
  
  cache:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - poktnet

  metricsdb:
    image: timescale/timescaledb:2.0.2-pg12
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=gatewaydb
    ports:
      - 5432:5432
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=gatewaydb
    ports:
      - 5432:5432
    networks:
      - poktnet

  fullnode.pokt:
    image: poktnetwork/pocket-core:RC-0.5.0.2
    user: root
    entrypoint: "/bin/sh -c"
    # command: ["/bin/init.sh /tmp/keyfile.json", "&&", "pocket", "start", "--keybase=false", "--datadir=/home/app/.pocket/"]
    command: "'/bin/init.sh /tmp/keyfile.json && pocket start --keybase=false --datadir=/home/app/.pocket/ --altruism'"
    env_file:
      - ./.fullnode.pokt.env
    ports:
      - "26656:26656"
      - "26657:26657"
      - "8081:8081"
      - "26660:26660"
    expose:
      - "8081"
      - "26656"
      - "26660"
    volumes:
      - ./scripts/init.sh:/bin/init.sh
      - ./config/keyfile.json:/tmp/keyfile.json
      - ./config/config.json:/tmp/config.json
      - ./config/chains.json:/tmp/chains.json
      - ./config/genesis.json:/tmp/genesis.json        
      - ./data/poktfullnode0:/home/app/.pocket/
      - ./data/poktfullnode0/crypto:/home/app/crypto
    networks:
      - poktnet
  
  ipfs:
    container_name: ipfs0
    image: ipfs/go-ipfs:release
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./data/ipfs0:/data/ipfs
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay
