version: "3.5"

services:
  pocketjs:
    container_name: pokt-aps-sdk
    volumes:
      - sourecode.pocketjs.volume:/usr/src/pocketjs
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  portal-api:
    container_name: pokt-fdt-portal-api
    command: >
      /bin/sh -c "\
        npm config set unsafe-perm true; \
        cp -ar /usr/src/pocketjs /usr/src/compiled-pocketjs; \
        cd /usr/src/compiled-pocketjs; \
        npm link; \
        cd /usr/src/gateway; \
        npm link @pokt-network/pocket-js; \
        npm install; \
        npm run start:watch;
      "
    env_file:
      - ${CWD}/stacks/pokt-fdt/dev/.portal-api.env
    volumes:
      - "${GATEWAY_REPO_PATH}/src:/usr/src/gateway/src:rw"
      - "${GATEWAY_REPO_PATH}/dist:/usr/src/gateway/dist:rw"
      - sourecode.pocketjs.volume:/usr/src/pocketjs
    ports:
      - 3000:3000
    networks:
      - poktnet
    depends_on:
      - pocketjs
      - db
      - cache
      - metricsdb
      - nodea.dev.pokt
      - nodeb.dev.pokt
      - nodec.dev.pokt

  db:
    networks:
      - poktnet

  cache:
    networks:
      - poktnet

  metricsdb:
    networks:
      - poktnet

  nodea.dev.pokt:
    networks:
      - poktnet

  nodeb.dev.pokt:
    networks:
      - poktnet

  nodec.dev.pokt:
    networks:
      - poktnet

  ipfs:
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay

volumes:
  sourecode.pocketjs.volume:
    driver: local
    driver_opts:
      type: bind
      device: ${POCKETJS_REPO_PATH}
      o: bind
