version: "3.5"

services:

  validator-a.pokt.prod.dockerhub:
    image: poktnetwork/pocket-core:RC-0.6.3
    entrypoint: "/bin/sh -c"
    command: "'/bin/init.sh /tmp/keyfile.json && pocket start --profileApp --simulateRelay --seeds=$POCKET_CORE_SEEDS  --datadir=/home/app/.pocket/'"
    env_file:
      - ./.validator-a.pokt.env
    ports:
      - "8081:8081"
      - "26657:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
    volumes:
      - ./scripts/init.sh:/bin/init.sh
      - ./config/keyfile.json:/tmp/keyfile.json
      - ./config/config.json:/tmp/config.jsor
      - ./config/chains.json:/tmp/chains.json
      - ./config/genesis.json:/tmp/genesis.json
        # - ./data/poktfullnode0:/home/app/.pocket/
        #    - ./data/poktfullnode0/crypto:/home/app/crypto
    networks:
      - poktnet

  validator-b.pokt.prod.dockerhub:
    image: poktnetwork/pocket-core:RC-0.6.3
    entrypoint: "/bin/sh -c"
    command: "'/bin/init.sh /tmp/keyfile.json && pocket start --profileApp --simulateRelay --seeds=$POCKET_CORE_SEEDS --datadir=/home/app/.pocket/'"
    env_file:
      - ./.validator-b.pokt.env
    ports:
      - "8082:8081"
      - "26658:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
    volumes:
      - ./scripts/init.sh:/bin/init.sh
      - ./config/keyfile.json:/tmp/keyfile.json
      - ./config/config.json:/tmp/config.jsor
      - ./config/chains.json:/tmp/chains.json
      - ./config/genesis.json:/tmp/genesis.json
        #  - ./data/poktfullnode0:/home/app/.pocket/
        #     - ./data/poktfullnode0/crypto:/home/app/crypto
    networks:
      - poktnet

  validator-c.pokt.prod.dockerhub:
    image: poktnetwork/pocket-core:RC-0.6.3
    entrypoint: "/bin/sh -c"
    command: "'/bin/init.sh /tmp/keyfile.json && pocket start --profileApp --simulateRelay --seeds=$POCKET_CORE_SEEDS --datadir=/home/app/.pocket/'"
    env_file:
      - ./.validator-c.pokt.env
    ports:
      - "8083:8081"
      - "26659:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
    volumes:
      - ./scripts/init.sh:/bin/init.sh
      - ./config/keyfile.json:/tmp/keyfile.json
      - ./config/config.json:/tmp/config.jsor
      - ./config/chains.json:/tmp/chains.json
      - ./config/genesis.json:/tmp/genesis.json
        #  - ./data/poktfullnode0:/home/app/.pocket/
        #  - ./data/poktfullnode0/crypto:/home/app/crypto
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay
