version: "3.5"

services:

  fullnode.pokt:
    image: poktnetwork/pocket-core:RC-0.5.0.2
    user: root
    entrypoint: "/bin/sh -c"
    # command: ["/bin/init.sh /tmp/keyfile.json", "&&", "pocket", "start", "--keybase=false", "--datadir=/home/app/.pocket/"]
    command: "'/bin/init.sh /tmp/keyfile.json && pocket start --keybase=false --datadir=/home/app/.pocket/ --altruism'"
    env_file:
      - ./.fullnode.pokt.env
    ports:
      - "26656:26656"
      - "26657:26657"
      - "8081:8081"
      - "26660:26660"
    expose:
      - "8081"
      - "26656"
      - "26660"
    volumes:
      - ./scripts/init.sh:/bin/init.sh
      - ./config/keyfile.json:/tmp/keyfile.json
      - ./config/config.json:/tmp/config.json
      - ./config/chains.json:/tmp/chains.json
      - ./config/genesis.json:/tmp/genesis.json
      - ./data/poktfullnode0:/home/app/.pocket/
      - ./data/poktfullnode0/crypto:/home/app/crypto
    networks:
      - poktnet


networks:
  poktnet:
    driver: overlay
