version: "3.5"

services:
  pocketjs:
    volumes:
      - shared:/usr/src/pocketjs
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  gateway:
    image: pocket-network/gateway
    build:
      context: ${GATEWAY_REPO_PATH}
      dockerfile: ./Dockerfile
    command: >
      /bin/sh -c "
        cd /usr/src/pocketjs \
        npm link @pokt-network/pocket-js \
        npm install \
        npm run start:watch
      "
    env_file:
      - ./.gateway.env
    volumes:
      - "${GATEWAY_REPO_PATH}/src:/usr/src/gateway/src"
      - "${GATEWAY_REPO_PATH}/dist:/usr/src/gateway/dist"
      - shared:/usr/src/pocketjs
    ports:
      - 3000:3000
    networks:
      - poktnet

  db:
    networks:
      - poktnet
  
  cache:
    networks:
      - poktnet

  metricsdb:
    networks:
      - poktnet

  fullnode.pokt:
    networks:
      - poktnet

  ipfs:
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay

volumes:
  shared: