version: "3.5"

services:

  nodea.dev.pokt:
    image: poktnetwork/pocket-core:dev-local
    build:
      context: ${POCKET_CORE_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-net/dev-tm/Dockerfile
      args:
        - POCKET_CORE_REPO_PATH=${POCKET_CORE_REPO_PATH}
        - POCKET_NETWORK_TENDERMINT_PATH=${POCKET_NETWORK_TENDERMINT_PATH}
    command: "/usr/bin/expect /home/app/.pocket/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev-tm/.nodea.dev.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1234
    ports:
      - "8081:8081"
      - "26657:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1234"
    volumes:
      - ${CWD}/docker/pokt-net/dev-tm/local_command_dev.sh:/home/app/.pocket/local_command_dev.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/dev-tm/config/config.nodea.dev.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.nodea.pokt.dev:/home/app/.pocket/data
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
      - "${POCKET_NETWORK_TENDERMINT_PATH}:/go/src/github.com/pokt-network/tendermint"
    networks:
      - poktnet

  nodeb.dev.pokt:
    image: poktnetwork/pocket-core:dev-local
    build:
      context: ${POCKET_CORE_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-net/dev-tm/Dockerfile
    command: "/usr/bin/expect /home/app/.pocket/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev-tm/.nodeb.dev.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1235
    ports:
      - "8082:8081"
      - "26658:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1235"
    volumes:
      - ${CWD}/docker/pokt-net/dev-tm/local_command_dev.sh:/home/app/.pocket/local_command_dev.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/dev-tm/config/config.nodeb.dev.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.nodeb.pokt.dev:/home/app/.pocket/data
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
      - "${POCKET_NETWORK_TENDERMINT_PATH}:/go/src/github.com/pokt-network/tendermint"
    networks:
      - poktnet

  nodec.dev.pokt:
    image: poktnetwork/pocket-core:dev-local
    build:
      context: ${POCKET_CORE_REPO_PATH}
      dockerfile: ${CWD}/docker/pokt-net/dev-tm/Dockerfile
    command: "/usr/bin/expect /home/app/.pocket/local_command_dev.sh"
    env_file:
      - ${CWD}/stacks/pokt-net/dev-tm/.nodec.dev.env
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=1236
    ports:
      - "8083:8081"
      - "26659:26657"
    expose:
      - "8081"
      - "26656"
      - "26657"
      - "46656"
      - "1236"
    volumes:
      - ${CWD}/docker/pokt-net/dev-tm/local_command_dev.sh:/home/app/.pocket/local_command_dev.sh
      - ${CWD}/stacks/pokt-net/shared/chains.json:/home/app/.pocket/config/chains.json
      - ${CWD}/stacks/pokt-net/shared/genesis.json:/home/app/.pocket/config/genesis.json
      - ${CWD}/stacks/pokt-net/dev-tm/config/config.nodec.dev.json:/home/app/.pocket/config/config.json
      - ${CWD}/data/pokt-net.nodec.pokt.dev:/home/app/.pocket/data
      - "${POCKET_CORE_REPO_PATH}:/go/src/github.com/pokt-network/pocket-core"
      - "${POCKET_NETWORK_TENDERMINT_PATH}:/go/src/github.com/pokt-network/tendermint"
    networks:
      - poktnet

networks:
  poktnet:
    driver: overlay
